import Link from 'next/link';
import { requireUser } from '@/lib/auth/require-role';
import { getStudentDashboard } from '@/lib/study/student-service';

export default async function StudentProgressPage() {
  const { user } = await requireUser('/aluno/progresso');
  const journey = await getStudentDashboard(user.id);
  return <div className="student-page"><header className="student-page-head"><span className="eyebrow">Minha jornada</span><h1>Seu progresso</h1><p>Cada aula concluída é um passo. Seu histórico permanece aqui mesmo quando seu acesso muda.</p></header><div className="student-stat-grid"><article><span>Sequência de estudo</span><strong>{journey.streak} dias</strong></article><article><span>Aulas iniciadas</span><strong>{journey.summary.started}</strong></article><article><span>Aulas concluídas</span><strong>{journey.summary.completed}</strong></article><article><span>Salvas</span><strong>{journey.favoriteIds.length}</strong></article></div><section className="student-panel"><div className="student-section-head"><h2>Por ciclo</h2><Link href="/aluno/disciplinas">Explorar aulas ↗</Link></div>{journey.summary.byCycle.length ? <ul className="student-cycle-list">{journey.summary.byCycle.map((cycle) => <li key={cycle.cycle}><span>{cycle.cycle}</span><strong>{cycle.completed} de {cycle.started} concluídas</strong></li>)}</ul> : <div className="student-empty"><h3>Uma jornada começa com a primeira aula.</h3><p>Seu acompanhamento será exibido aqui assim que você iniciar seus estudos.</p></div>}</section><section className="student-panel"><h2>Estudadas recentemente</h2>{journey.recentProgress.length ? <ul className="student-cycle-list">{journey.recentProgress.map((progress) => { const lesson = journey.lessons.find((item) => item.id === progress.lesson_id); return <li key={progress.lesson_id}><span>{lesson?.title ?? 'Conteúdo anterior'}</span>{lesson ? <Link href={`/aluno/disciplinas/${lesson.id}`}>{progress.completed_at ? 'Concluída' : 'Retomar'} →</Link> : <strong>{progress.completed_at ? 'Concluída' : 'Iniciada'}</strong>}</li>; })}</ul> : <p className="student-muted">Nenhuma aula iniciada ainda.</p>}</section></div>;
}
