import { randomUUID } from 'node:crypto';
import { createClient } from '@supabase/supabase-js';
import { expect, test } from '@playwright/test';

test('imported lessons: premium, persistence, expiry and direct RLS', async ({ page, context }) => {
  test.skip(process.env.MEDHELP_E2E_LOCAL !== '1', 'Requires disposable local Supabase');
  test.setTimeout(90_000);
  const url=process.env.NEXT_PUBLIC_SUPABASE_URL!;
  expect(url).toBe('http://127.0.0.1:54321');
  const key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!;
  const admin=createClient(url,process.env.MEDHELP_E2E_LOCAL_SERVICE_KEY!,{auth:{persistSession:false,autoRefreshToken:false}});
  const { data:lesson,error:lessonError }=await admin.from('lessons').select('id,title').eq('slug','eb-04-a1').eq('status','published').single();
  expect(lessonError, 'Real compiled lesson fixture must be imported and published first').toBeNull();
  expect(lesson).not.toBeNull();
  const id=lesson!.id;
  const email=`journey-${randomUUID()}@medhelp.test`;
  const password=`Study-${randomUUID()}!`;
  const created=await admin.auth.admin.createUser({email,password,email_confirm:true});
  expect(created.error).toBeNull();
  const userId=created.data.user!.id;
  const client=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});
  const signed=await client.auth.signInWithPassword({email,password});
  expect(signed.error).toBeNull();
  const login=async () => {
    await page.goto(`/entrar?next=${encodeURIComponent(`/aluno/disciplinas/${id}`)}`);
    await page.getByLabel('E-mail',{exact:true}).fill(email);
    await page.getByLabel('Senha',{exact:true}).fill(password);
    await page.getByRole('button',{name:'Entrar',exact:true}).click();
    await expect(page).toHaveURL(new RegExp(`/aluno/disciplinas/${id}$`));
  };
  await login();
  await expect(page.getByRole('heading',{name:'Continue sua jornada com o Premium'})).toBeVisible();
  let blocks=await client.from('lesson_blocks').select('content').eq('lesson_id',id);
  expect(blocks.error).toBeNull();
  expect(blocks.data).toEqual([]);
  const grant=await admin.from('subscriptions').insert({user_id:userId,state:'active',access_until:new Date(Date.now()+86_400_000).toISOString()});
  expect(grant.error).toBeNull();
  await page.reload();
  const content=page.getByRole('region',{name:'Conteúdo da aula'});
  await expect(content).toBeVisible();
  await expect(content.getByRole('table').first()).toBeVisible();
  await content.getByRole('region',{name:'Tabela da aula'}).focus();
  await expect(content.getByRole('region',{name:'Tabela da aula'})).toBeFocused();
  await expect(content).toContainText(/Quest|Exerc|Pratique/i);
  await expect(content).toContainText(/Referências|Fontes/);
  await page.getByRole('button',{name:'Marcar como concluída'}).click();
  await expect(page.getByRole('button',{name:'✓ Aula concluída'})).toBeDisabled();
  await page.getByRole('button',{name:'♡ Salvar aula'}).click();
  await expect(page.getByRole('button',{name:'♥ Salva'})).toHaveAttribute('aria-pressed','true');
  await context.clearCookies();
  await login();
  await expect(page.getByRole('button',{name:'✓ Aula concluída'})).toBeDisabled();
  await expect(page.getByRole('button',{name:'♥ Salva'})).toHaveAttribute('aria-pressed','true');
  const before=await client.from('lesson_progress').select('*').eq('lesson_id',id).single();
  expect(before.error).toBeNull();
  expect(before.data?.completed_at).toBeTruthy();
  const expired=await admin.from('subscriptions').update({state:'expired',access_until:new Date(Date.now()-86_400_000).toISOString()}).eq('user_id',userId);
  expect(expired.error).toBeNull();
  await page.reload();
  await expect(page.getByRole('heading',{name:'Continue sua jornada com o Premium'})).toBeVisible();
  await expect(content).toHaveCount(0);
  blocks=await client.from('lesson_blocks').select('content').eq('lesson_id',id);
  expect(blocks.error).toBeNull();
  expect(blocks.data).toEqual([]);
  const after=await client.from('lesson_progress').select('*').eq('lesson_id',id).single();
  expect(after.error).toBeNull();
  expect(after.data).toEqual(before.data);
  const favorite=await client.from('favorites').select('lesson_id').eq('lesson_id',id).single();
  expect(favorite.error).toBeNull();
  expect(favorite.data?.lesson_id).toBe(id);
  // No cleanup against remote services: the entire local container is discarded by CI.
});
