import Link from 'next/link';
import { requireUser } from '@/lib/auth/require-role';
import { getStudentDashboard } from '@/lib/study/student-service';

export default async function StudentPage() {
  const { user } = await requireUser('/aluno');
  const journey = await getStudentDashboard(user.id);
  const firstName = journey.name.trim().split(/\s+/)[0];
  const percent = journey.lessons.length ? Math.round(journey.summary.completed / journey.lessons.length * 100) : 0;
  return <div className="student-page">
    <section className="student-hero"><div><span className="eyebrow">Seu espaço de aprendizado</span><h1>Olá, {firstName}.<br /><em>Vamos continuar?</em></h1><p>Um passo por dia faz a diferença. Seu ritmo, suas conquistas, sua jornada.</p><Link className="mh-button mh-button--primary" href={journey.continueLesson ? `/aluno/disciplinas/${journey.continueLesson.id}` : '/aluno/disciplinas'}>{journey.continueLesson ? 'Continuar estudando ↗' : 'Explorar disciplinas ↗'}</Link></div><div className="student-hero__stat"><span>Jornada em movimento</span><strong>{percent}%</strong><p>{journey.summary.completed} de {journey.lessons.length} aulas concluídas</p><div className="student-meter"><span style={{ width: `${percent}%` }} /></div></div></section>
    <div className="student-stat-grid"><article><span>✦ Sequência</span><strong>{journey.streak} {journey.streak === 1 ? 'dia' : 'dias'}</strong><small>Continue no seu ritmo</small></article><article><span>◉ Aulas iniciadas</span><strong>{journey.summary.started}</strong><small>Uma aula de cada vez</small></article><article><span>✓ Concluídas</span><strong>{journey.summary.completed}</strong><small>Conhecimento construído</small></article><article><span>♡ Favoritos</span><strong>{journey.favoriteIds.length}</strong><small>Para revisitar depois</small></article></div>
    <div className="student-columns"><section className="student-panel"><div className="student-section-head"><div><span className="eyebrow">Próximo passo</span><h2>Continue de onde parou</h2></div><Link href="/aluno/disciplinas">Ver disciplinas ↗</Link></div>{journey.continueLesson ? <Link className="student-feature" href={`/aluno/disciplinas/${journey.continueLesson.id}`}><span>{journey.continueLesson.cycle} · {journey.continueLesson.discipline}</span><h3>{journey.continueLesson.title}</h3><p>Retome a aula e mantenha sua jornada ativa.</p><b>Ir para aula <span aria-hidden="true">→</span></b></Link> : <div className="student-empty"><span aria-hidden="true">◌</span><h3>Seu próximo capítulo começa aqui.</h3><p>As aulas publicadas aparecerão neste espaço. Enquanto isso, conheça o catálogo e o Atlas.</p><Link href="/explorar">Conhecer o catálogo →</Link></div>}</section><section className="student-panel"><div className="student-section-head"><div><span className="eyebrow">Visão geral</span><h2>Sua trajetória</h2></div><Link href="/aluno/progresso">Detalhes ↗</Link></div>{journey.summary.byCycle.length ? <ul className="student-cycle-list">{journey.summary.byCycle.map((cycle) => <li key={cycle.cycle}><span>{cycle.cycle}</span><strong>{cycle.completed}/{cycle.started} aulas</strong></li>)}</ul> : <p className="student-muted">Ao iniciar uma aula, seu progresso por ciclo aparecerá aqui.</p>}<div className="student-access"><span>✧ Seu acesso</span><strong>{journey.premiumAccess ? 'Premium ativo' : 'Conteúdos gratuitos'}</strong><Link href="/#preco">Conhecer os planos →</Link></div></section></div>
    <section className="student-banner"><div><span className="eyebrow">Explore mais</span><h2>O corpo humano, sob uma nova perspectiva.</h2><p>Visite o Atlas anatômico interativo e descubra estruturas em detalhe.</p></div><Link className="mh-button mh-button--secondary" href="/#atlas">Explorar Atlas ↗</Link></section>
  </div>;
}
