import Link from 'next/link';
import { requireUser } from '@/lib/auth/require-role';
import { getStudentFlashcards } from '@/lib/study/flashcard-service';
import { FlashcardSession } from './flashcard-session';

export default async function FlashcardsPage() {
  const { user } = await requireUser('/aluno/flashcards');
  const study = await getStudentFlashcards(user.id);
  return <div className="student-page"><header className="student-page-head"><span className="eyebrow">Revisão espaçada</span><h1>Flashcards</h1><p>Reveja o essencial no momento certo. Responda com sinceridade para ajustar o ritmo das próximas revisões.</p></header><div className="student-stat-grid"><article><span>Prontos hoje</span><strong>{study.queue.length}</strong><small>Cartões para estudar agora</small></article><article><span>Na sua coleção</span><strong>{study.totalCards}</strong><small>Cartões disponíveis</small></article><article><span>Baralhos</span><strong>{study.decks.length}</strong><small>Temas publicados</small></article><article><span>Próxima revisão</span><strong className="flashcard-next-due">{study.nextDue ? new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: 'short', timeZone: 'UTC' }).format(new Date(study.nextDue)) : '—'}</strong><small>{study.nextDue ? 'Confira quando chegar' : 'Seu ritmo está em dia'}</small></article></div>{study.queue.length ? <FlashcardSession cards={study.queue} /> : <section className="student-empty student-empty--wide"><span aria-hidden="true">✦</span><h2>{study.decks.length ? 'Tudo em dia por enquanto.' : 'Os cartões estão chegando.'}</h2><p>{study.decks.length ? 'Você respondeu todos os cartões disponíveis para hoje. Volte quando a próxima revisão estiver pronta.' : 'Assim que os primeiros baralhos forem publicados, sua rotina de revisão aparecerá aqui.'}</p><Link href="/aluno/disciplinas">Explorar disciplinas →</Link></section>}{study.lockedDecks.length > 0 && <section className="student-panel flashcard-decks"><span className="eyebrow">Continue explorando</span><h2>Baralhos Premium</h2><p>Mais temas para revisar no seu ritmo, disponíveis com a assinatura.</p><div>{study.decks.filter((deck) => study.lockedDecks.includes(deck.id)).map((deck) => <article key={deck.id}><strong>{deck.title}</strong><span>{deck.description ?? 'Conteúdo de revisão MEDHELP'}</span></article>)}</div><Link href="/#preco">Conhecer o plano ↗</Link></section>}</div>;
}
